// Regenerates src/data/hostedFlags.ts from manifest.json, keyed by the
// canonical Commons filename (canonName) the app looks up.
//   node scripts/flags/cf/genhosted.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { MAN, OUT, canonName } from "./common.mjs"

const man = JSON.parse(readFileSync(MAN, "utf8"))
const map = {}
let missingFile = 0
for (const [name, p] of Object.entries(man)) {
  if (!existsSync(OUT + p.slice("/cf".length))) { missingFile++; continue }
  const k = canonName(name)
  map[k] = p // later manifest entries win, as before
}
const keys = Object.keys(map).sort()
const lines = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
writeFileSync("src/data/hostedFlags.ts",
`// AUTO-GENERATED by scripts/flags/cf/genhosted.mjs (reads the self-host manifest).
// Supplements LOCAL_FLAGS: maps a canonical Wikimedia Commons filename (see
// canonName in hostedUrl.ts) to a self-hosted copy under /cf/. Anything absent
// falls back to the live Commons hotlink, so a partial set is always safe.
// Do not hand-edit.
export const HOSTED_FLAGS: Record<string, string> = {
${lines.join("\n")}
}
`)
console.log("HOSTED_FLAGS entries:", keys.length, missingFile ? `(skipped ${missingFile} manifest entries with no file)` : "")
