// The main colours of every country flag, largest first, for Flag Studio's
// colour mixing ("this flag in that flag's colours"). Each flag is drawn the
// way the studio draws it (official artwork when we have it), its pixels are
// counted, and near-identical shades are merged; colours under 1.5% of the flag
// (crest details, outlines) are left out. Writes src/data/flagPalettes.ts.
//
// Needs Playwright, which isn't a project dependency:
//   npm i --no-save playwright && node --experimental-strip-types --import ./scripts/ts-resolve.mjs scripts/flags/palettes.mjs
// (set CHROMIUM=/path/to/chrome to use an installed browser)
import fs from 'node:fs'
import path from 'node:path'

const pw = await import(process.env.PLAYWRIGHT || 'playwright')
const { chromium } = pw.chromium ? pw : pw.default
const ROOT = path.resolve(import.meta.dirname, '../..')
const data = f => import(path.join(ROOT, 'src/data', f))
const { FLAGS } = await data('flags.ts')
const { STUDIO_FLAGS } = await data('studioFlags.ts')

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined, args: ['--headless=new'] })
const page = await browser.newPage()
const out = {}
for (const f of FLAGS) {
  const code = f.code.toLowerCase()
  const file = STUDIO_FLAGS[code]?.[0] ?? f.flagUrl   // same choice as countryBase()
  const svg = fs.readFileSync(path.join(ROOT, 'public', file)).toString('base64')
  out[f.code] = await page.evaluate(async src => {
    const img = new Image()
    img.src = src
    await img.decode()
    const W = 480, H = Math.max(1, Math.round(W * img.naturalHeight / img.naturalWidth)) || 160
    const c = document.createElement('canvas'); c.width = W; c.height = H
    const ctx = c.getContext('2d')
    ctx.drawImage(img, 0, 0, W, H)
    const px = ctx.getImageData(0, 0, W, H).data
    const counts = new Map()
    for (let i = 0; i < px.length; i += 4) {
      if (px[i + 3] < 250) continue   // transparent corners (Nepal) and soft edges
      const k = (px[i] << 16) | (px[i + 1] << 8) | px[i + 2]
      counts.set(k, (counts.get(k) ?? 0) + 1)
    }
    const total = [...counts.values()].reduce((a, b) => a + b, 0)
    const rgb = k => [k >> 16, (k >> 8) & 255, k & 255]
    const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2])
    // Distance from c to the line between two colours: edge pixels where red
    // meets white come out pink, and aren't colours of the flag.
    const toSegment = (c, a, b) => {
      const ab = [0, 1, 2].map(i => b[i] - a[i]), ac = [0, 1, 2].map(i => c[i] - a[i])
      const len = ab.reduce((s, v) => s + v * v, 0) || 1
      const t = Math.max(0, Math.min(1, ab.reduce((s, v, i) => s + v * ac[i], 0) / len))
      return dist(c, [0, 1, 2].map(i => a[i] + t * ab[i]))
    }
    const groups = []
    for (const [k, n] of [...counts.entries()].sort((a, b) => b[1] - a[1])) {
      const c = rgb(k)
      const g = groups.find(g => dist(g.c, c) <= 40)
      if (g) { g.n += n; continue }
      const big = groups.filter(g => g.n / total >= 0.015)
      if (big.some((a, i) => big.some((b, j) => j > i && toSegment(c, a.c, b.c) <= 18))) continue
      groups.push({ c, n })
    }
    const hex = c => '#' + c.map(v => v.toString(16).padStart(2, '0')).join('')
    return groups.sort((a, b) => b.n - a.n).filter(g => g.n / total >= 0.015).slice(0, 6).map(g => [hex(g.c), Math.round(g.n / total * 100)])
  }, `data:image/svg+xml;base64,${svg}`)
}
await browser.close()

const ts = `// Generated by scripts/flags/palettes.mjs: each country flag's main colours,
// largest first, as [hex, % of the flag]. Used by Flag Studio's colour mixing.
export const FLAG_PALETTES: Record<string, [string, number][]> = {
${Object.entries(out).map(([c, p]) => `  ${c}: ${JSON.stringify(p)},`).join('\n')}
}
`
fs.writeFileSync(path.join(ROOT, 'src/data/flagPalettes.ts'), ts)
console.log(`[palettes] ${Object.keys(out).length} flags`)
