// Flag Studio opens real flags at their official proportions. Our quiz artwork
// (public/flags, flag-icons) is all 4:3, so the studio uses the Wikimedia
// Commons version instead: the copy we already self-host under /cf/ when there
// is one, otherwise a copy downloaded here into public/studio-flags/.
//
// Writes src/data/studioFlags.ts: code -> [file, width/height].
//   node scripts/flags/studioFlags.mjs
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '../..')
const DL_DIR = path.join(ROOT, 'public/studio-flags')

const hostedTs = fs.readFileSync(path.join(ROOT, 'src/data/hostedFlags.ts'), 'utf8')
const HOSTED = new Map([...hostedTs.matchAll(/^\s*"([^"]+)":\s*"([^"]+)"/gm)].map(m => [m[1], m[2]]))
const flagsTs = fs.readFileSync(path.join(ROOT, 'src/data/flags.ts'), 'utf8')
const FLAGS = [...flagsTs.matchAll(/f\('([A-Z-]+)','((?:[^'\\]|\\.)+)'/g)].map(m => [m[1].toLowerCase(), m[2].replace(/\\'/g, "'")])

// Commons names that don't follow "Flag_of_<name>.svg".
const ALIAS = {
  cd: 'Flag_of_the_Democratic_Republic_of_the_Congo.svg',
  gm: 'Flag_of_The_Gambia.svg',
  tl: 'Flag_of_East_Timor.svg',
  bo: 'Flag_of_Bolivia_(state).svg',
  cr: 'Flag_of_Costa_Rica_(state).svg',
  ci: "Flag_of_Côte_d'Ivoire.svg",
  ae: 'Flag_of_the_United_Arab_Emirates.svg',
  cf: 'Flag_of_the_Central_African_Republic.svg',
}
// Keep the quiz artwork where Commons shows a different flag from the app.
const KEEP_QUIZ_ART = new Set(['af'])

// A browser sizes an SVG by its width/height when both are set (Qatar's file
// stretches a 75×18 viewBox to 1400×550), otherwise by its viewBox.
const ratioOf = svg => {
  const tag = svg.match(/<svg[^>]*>/)?.[0] ?? ''
  const w = tag.match(/\swidth="([\d.]+(?:e\d+)?)(px)?"/), h = tag.match(/\sheight="([\d.]+(?:e\d+)?)(px)?"/)
  if (w && h && +w[1] > 0 && +h[1] > 0) return +w[1] / +h[1]
  const vb = tag.match(/viewBox="\s*([-\d.e]+)[\s,]+([-\d.e]+)[\s,]+([\d.e]+)[\s,]+([\d.e]+)/)
  return vb ? +vb[3] / +vb[4] : null
}

fs.mkdirSync(DL_DIR, { recursive: true })
const out = []
for (const [code, name] of FLAGS) {
  if (KEEP_QUIZ_ART.has(code)) continue
  const n = name.replace(/ /g, '_')
  const file = ALIAS[code] ?? [`Flag_of_${n}.svg`, `Flag_of_the_${n}.svg`].find(f => HOSTED.has(f)) ?? `Flag_of_${n}.svg`
  let url = HOSTED.get(file)
  let svg
  if (url) {
    svg = fs.readFileSync(path.join(ROOT, 'public', url), 'utf8')
  } else {
    const local = path.join(DL_DIR, `${code}.svg`)
    if (!fs.existsSync(local)) {
      const res = await fetch(`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}`, { headers: { 'User-Agent': 'globalio.app flag studio (sjoudrie@gmail.com)' } })
      if (!res.ok) { console.warn(`[studio-flags] ${code}: ${file} -> ${res.status}`); continue }
      fs.writeFileSync(local, await res.text())
    }
    svg = fs.readFileSync(local, 'utf8')
    url = `/studio-flags/${code}.svg`
  }
  const ratio = ratioOf(svg)
  if (!ratio || !svg.includes('<svg')) { console.warn(`[studio-flags] ${code}: unreadable`); continue }
  out.push([code, url, +ratio.toFixed(4), file])
}

const ts = `// Generated by scripts/flags/studioFlags.mjs. The Wikimedia Commons version of
// each country flag, at its official proportions, for Flag Studio.
// code -> [file, width / height]
export const STUDIO_FLAGS: Record<string, [string, number]> = {
${out.map(([c, u, r, f]) => `  ${JSON.stringify(c)}: [${JSON.stringify(u)}, ${r}], // ${f}`).join('\n')}
}
`
fs.writeFileSync(path.join(ROOT, 'src/data/studioFlags.ts'), ts)
console.log(`[studio-flags] ${out.length} of ${FLAGS.length} flags (${fs.readdirSync(DL_DIR).length} downloaded)`)
